### ISSUE TITLE
Проблема при сборке

### ISSUE THREAD

**Issue by AxxxSxxx** [forth32/qhuaweiflash#14]
QT5
qmake - норма
а make
...
ptable.cpp:7:10: fatal error: zlib.h: Нет такого файла или каталога
 #include <zlib.h>
compilation terminated.
Makefile:619: recipe for target 'ptable.o' failed
make: *** [ptable.o] Error 1

**Comment by forth32** [comment]
Установи библиотеку zlib. Для дебианоподобных ОС это пакет zlib1g-dev.

**Comment by AxxxSxxx** [comment]
Установил, процесс пошел. Спасибо!
