### ISSUE TITLE
Can you port this code to windows too?

### ISSUE THREAD

**Issue by Njunwa1** [forth32/qhuaweiflash#3]
The are alot of usages of libraries that make this code only compile on Unix system alone like the use the use of "termios" or The use of bzero() on line 300 and 520 makes this code not to compile on Windows and this function is deprecated or less one has to define something like this below,
#define bzero(b,len) (memset((b), '\0', (len)), (void) 0)

**Comment by forth32** [comment]
I do not use fucked windows and do not going to port this code to other OSes.
