### ISSUE TITLE
Неполное что-то беспорядочное

### ISSUE THREAD

**Issue by Zaraky2008** [forth32/qhuaweiflash#4]
При попытке создать его, он показывает ПРЕДУПРЕЖДЕНИЕ: Не удалось найти: ulpatcher.cpp
ВНИМАНИЕ: Не удалось найти: ulpatcher.h
2 файла упоминаются в Makefile, но не отображаются здесь .. являются ли программы неполными?

**Comment by forth32** [comment]
добавил.

**Comment by Zaraky2008** [comment]
спасибо
